<h1>Karácsonyi ajándék</h1>
<pre>Szerző: Vaszilij | 2022. dec. 25. | <a href="?oldal=novella">Novella</a></pre>
<div class="kozepre">
<a href="images/novella/karacsony.jpg" data-lightbox="Karacsony">
<img class="img-fluid nagy" src="images/novella/karacsony.jpg" title="Karácsonyi ajándék" alt="Karácsonyi ajándék" class="nagy"/>
</a>
<p>Akkoriban a tél még tél volt. Gyerekként persze minden nagyobbnak és jelentőségteljesebbnek tűnik, de az internetes archívumokban bőven találni felvételeket embermagas hótorlaszokról, elakadt járművekről és derékig a hóban taposó felnőttekről.</p>
<p>Azon a télen nem csak a saját házunk táján takarítottam a havat, hanem a szomszéd Piri néni portája előtt is. A férje a nyáron halt meg, ő pedig hangos, jó kedélyű asszonyból hetek alatt változott megtört, csendes, görnyedten járó nénivé. Senki nem kérte, hogy nála is lapátoljak, de valahogy természetesnek tűnt, hogy továbbmegyek a két ház kerítésének határán. Piri néni elfeledett, szürke ablakdíszként figyelt az ablakból, és amikor végeztem, erőtlenül odaintett nekem.</p>
<p>Aznap iskola után is havat lapátoltam, aztán egy bögre forró teával a konyhai konvektor elé húzódva próbáltam életet lehelni fagyott tagjaimba. Ezt szerettem a télben: a kinti hideget kizárva a melegből figyelni a lassanként elszürkülő utcákat.<br />Mikor eléggé kiolvadtam, és feltűnt, hogy farkaséhes vagyok, nekiálltam szendvicset készíteni magamnak. Mindent előkészítettem, aztán nyúltam a zsebembe a bicskámért. Döbbenten vettem észre, hogy nincs ott. Átforgattam az összes zsebet is, aztán a kabátomat, végül az iskolatáskám tartalmát is kiszórtam az ágyamra, de a bicskának hűlt helye volt.</p>
<p>Noha nem fűlt hozzá a fogam, újra felöltöztem, és kimentem az utcára. Korán sötétedett, de még elegendő fény volt ahhoz, hogy megláthassam a piros bicskát a hóban. Átnéztem a kertet, a ház előtti járdát, a Piri néni előtti részt, aztán kétségbeesetten elkezdtem áttúrni a nemrég összehordott hókupacokat. Hiába, a bicska nem került elő. Letörten, összefagyva mentem vissza a házba.</p>

<p>Csak vacsoránál, a hétvégéről megmarad gulyásleves és a frissen sülő bundás kenyér illatára bújtam elő a szobámból. A fűszeres, enyhén csípős leves isteni volt, én mégis kedvetlenül kanalaztam magamba.<br />&#8211; Miért lógatod az orrodat? &#8211; kérdezte anyám. &#8211; Csak nincs valami gond az iskolában?<br />&#8211; Nem. Csak a bicska. Elveszett.<br />&#8211; Ó. Akkor azt kerested olyan buzgón a hóban? &#8211; kérdezte. &#8211; Piri néni telefonált &#8211; tette hozzá meglepett pillantásomra.<br />&#8211; Igen. A suliban még megvolt, de hólapátolás után már nem találtam.<br />&#8211; Hát, sajnálom, de nem olyan nagy kár. <br />&#8211; Nem nagy kár? &#8211; döbbentem meg. &#8211; De az egy svájci bicska volt, Pavel bácsitól kaptam!<br />Apám kipillantott az újságja mögül.<br />&#8211; Annyira volt az a bicska svájci, mint amennyire Pavel bácsi cseh &#8211; mondta, aztán visszafordult a sporthírekhez.<br />Anyám ugyan vetett rá egy lesújtó pillantást &#8211; Pavel bácsi neki volt valamiféle rokona, máig nem tudom, milyen &#8211; aztán folytatta a kenyerek bundába bújtatását. Úgy tűnt, az eltűnt bicskám senkit sem érdekel.</p>
<p>Másnap szerencsére nem esett újabb hó, így aztán egyenesen hazafelé igyekeztem a buszmegállóból. Az utca csendes volt, itt-ott csúszós, mégis valahogy békességet árasztott a mindent belepő fehér takaró, ami mintha a hangokat is vattába burkolta volna.<br />Meglepetésemre Piri néni a háza ajtajában állt, és integetett, hogy menjek oda. Fekete, formátlan szoknyát és kabátot viselt, és egy sötétszürke kendőt tekert a válla köré. Meggörnyedt, mintha a lehető legkevesebbet szeretné mutatni magából a külvilágnak.<br />&#8211; Csókolom, Piri néni! Segíthetek valamiben? &#8211; kérdeztem odaérve.<br />&#8211; Szervusz, Gergő. Nem, nem azért hívlak. Csak hallottam a bicskádról.<br />&#8211; Sajnos elhagytam valahol. Pedig eredeti svájci volt &#8211; mondtam. Jólesett, hogy valaki végre komolyan vesz.<br />&#8211; Svájci. Az már valami! Mégis, egy férfi nem lehet bicska nélkül, mit gondolsz?<br />&#8211; Hát, szerintem sem. Majd nyáron elmegyek építőtáborba, és összegyűjtök egy újra valót.<br />&#8211; Derék. Derék. De addig is, mit szólnál ehhez? <br />Belenyúlt a kabátja zsebébe, elővett belőle egy bicskát, és felém nyújtotta. Emberes darabnak tűnt, fa nyéllel és érdekes, hullámos formával.<br />&#8211; Lajos bácsié volt &#8211; mondta. &#8211; Szerintem örülne, ha a tiéd lenne.<br />&#8211; Piri néni, én ezt nem fogadhatom el! De nagyon szép.<br />&#8211; Már a tiéd. Vigyázz rá! &#8211; A kezembe nyomta a bicskát, aztán sarkon fordult, és mint egy riadt veréb, beszökkent a házba.</p>
<p>Az új bicska, mint apámtól megtudtam, egy fejesgörbe volt. Bár látszott rajta, hogy Lajos bácsi sokat használta &#8211; a kifényesedett baknik, a fenés nyomai a pengén, és a nyél besötétedett fája mind ezt sugallták &#8211; remek állapotban volt. Vigyáztam rá, mint a szemem fényére, ezt semmiképp nem szerettem volna elveszíteni. Jó volt evéshez, farigcsáláshoz, meg mindenhez, amire egy kés kellhet egy embernek, én pedig nyitott szemmel jártam, kerestem az alkalmat, hogy használhassam a bicskát. Olykor meg csak gyönyörködtem benne: a fa erezetében, a réz játékában a fénnyel, a penge ívében.</p>

<p>Néhány nap múlva aztán kitört a téli szünet. Az utolsó iskolai nap fénypontja persze az ajándékozás volt, és noha örültünk a feldíszített teremnek, a süteményeknek és az osztályfőnök által készített teának, legjobban mégis azon izgult mindenki, hogy kitől és mit fog kapni.<br />Furcsa, arra nem emlékszem, hogy mit kaptam, de arra igen, hogy a Takács Andi borzasztóan örült a tőlem kapott könyvnek, én meg a dezodorillatú pusziknak. Épp ezt az élményt próbáltam megemészteni, amikor feltűnt a terem sarkából egy piros villanás. A hátsó padok biztonságában Fehér Feri épp a saját ajándékát bontogatta egy svájci bicskával.</p>
<p>Egy bögrével a kezemben elindultam felé. Igyekeztem olyan képet vágni, mint akit teljesen elvarázsoltak a mennyezetről lógó üveggömbök, az ablakra fújt hópelyhek és a fenyőfa friss illata. Fefe nem vett észre, buzgón küzdött a ragasztócsíkokkal és a csomagolás szalagjával. Ő viselt egyedül az osztályban ezen a napon is iskolaköpenyt &#8211; csak később, felnőtt fejjel jöttem rá, hogy ezzel próbálta leplezni a viseltes, elnyűtt ruháit, amelyek a bátyjai után maradtak rá.<br />Megálltam pár lépésre tőle, és figyeltem a bicskát. Semmi kétség: az enyém volt, ugyanazzal a jelöléssel a nyélen, ugyanazzal a két, párhuzamos karcolással a pengén, amelyeket egy tűzőkapocs okozott.</p>
<p>Fefe hirtelen észrevett, és ugrott egyet hátrafelé. Aztán kényszeredett vigyort erőltetett a képére, miközben igyekezett a bicskát becsukni, és elsüllyeszteni a zsebében.<br />&#8211; Mizu, Geri? Téged ki húzott? &#8211; érdeklődött.<br />Egy pillanatig nem tudtam, mit csináljak. Nekitámadjak, és megvádoljam, hogy ellopta, szóljak Kati néninek, vagy gondoljam ki, hogy miképp tudnám visszalopni a saját bicskámat. Aztán megtapogattam a zsebemben a fejesgörbét, és különös érzés szállt meg: ennek így kellett történnie. Fefének talán soha nem lett volna saját kése, így pedig mindketten gazdagodtunk valamivel ezen a karácsonyon.<br />&#8211; Boldog karácsonyt, Fefe! &#8211; mondtam, és odébb sétáltam.</p>

<p>Ha szeretnél naprakész lenni a bloggal kapcsolatban, akkor a <a href="https://www.facebook.com/VaszilijEdc">Facebook oldalon</a> találsz gyakori tartalmat.</p>
<p>Ha te is hozzájárulnál a késes tartalmak szaporításához, akkor a <a href="https://www.facebook.com/groups/434204628313605">Négyszögletű Pengeerdő</a> csoportban várunk szeretettel.</p>
</div>