<h1>Van egy késed?</h1>
<pre>Szerző: Vaszilij | 2022. nov. 20. | <a href="?oldal=novella">Novella</a></pre>
<div class="kozepre">
<a href="images/novella/vekes.jpg" data-lightbox="Vekes">
<img class="img-fluid nagy" src="images/novella/vekes.jpg" title="Van egy késed?" alt="Van egy késed?" class="nagy"/>
</a>
<p>  &#8211; Van egy késed? &#8211; kérdezte Svarci. Nyúlánk, vékony srác volt; a becenevét azért kapta, mert folyton edzésről készült videókat nézett, ilyen cikkeket olvasott, illetve főképp erről beszélt. Ki tudja, talán gyúrni is járt, bár nem látszott rajta.<br />  &#8211; Mire kell?<br />  &#8211; Meghozta a fehérjeporokat a futár, a csomagot szeretném kibontani.<br />  Biccentettem, aztán elővettem a táskámból a direkt erre a célra rendszeresített Ka-Bar Doziert. Elslattyogott vele az asztalához, két kézzel kinyitotta a kést, felvágta a pántolószalagot és a ragasztószalagot, majd megpróbálta becsukni a pengét. A szemem sarkából figyeltem, hogy mire jut a zárral, de egy-két perc elég volt neki, hogy rájöjjön a módszerre.<br />  &#8211; Köszi! &#8211; hozta vissza aztán, és letette az asztalomra. &#8211; Amúgy miért hordasz magadnál kést?<br />  &#8211; Hogy oda tudjam adni, ha kérnek egyet kölcsön &#8211; sóhajtottam.<br />  &#8211; Oké, nem úgy értem, tényleg köszi! Csak kicsit fura, nem?<br />  &#8211; Egészen addig, amíg nincs szükséged egyre.<br />  Röviden elgondolkodott, feljebb tolta a szemüvegét az orrnyergén, aztán visszament az asztalához.<br />  &#8211; Amúgy egész praktikus &#8211; szólalt meg pár perc múlva, amikor már azt hittem, rég a munkájába feledkezett. &#8211; Mármint ez a kés dolog.<br />  &#8211; Ahamm &#8211; hagytam rá a dolgot, és visszatértem én is a melóhoz.</p>
<p>  &#8211; Figyu, gondolkodtam.<br />  Svarci az asztalomnak támaszkodva állt, casual friday lévén farmerben és Under Armour kapucnis pulcsiban. &#8211; Szerintem te tudsz nekem segíteni. Mármint ebben a késes dologban.<br />  Meglepetten néztem rá.<br />  &#8211; Persze, attól függ.<br />  &#8211; Rendelnék egy kést, meg akartalak kérdezni róla. Kiszúrtam, hogy neked több is van, meg hogy váltogatod őket. Ehhez mit szólnál? &#8211; előszedte a telefonját, pötyögött rajta egy sort, aztán felém fordította a képernyőt.<br />  A bicska, amit megmutatott, mintha egy olyan ember tervezőasztaláról került volna ki, aki kizárólag akciófilmeket nézett, de a valóságban még nem látott kést soha. Tanto él, fogazott gerinc, brutális méretű markolat törővéggel és hevedervágóval, és az egész terepszínben. Nem lepett volna meg, ha valahogy egy elemlámpa is bele lett volna építve.<br />  &#8211; Huhh. Kissé&#8230; merész &#8211; nyögtem ki. &#8211; Nem gondolkodtál valami szolidabb darabban, amit esetleg használni is lehet?<br />  &#8211; Olyan jópofának néz ki, nem? De ha van más ötleted, akkor szívesen meghallgatom.<br />  Láttam rajta, hogy egy kicsit lelombozta, hogy nem lelkesedtem a választottjáért.<br />  &#8211; Akad &#8211; mondtam. &#8211; Készítek neked egy listát, átküldöm mélben, és megbeszéljük, oké?<br />  &#8211; Jól hangzik. Azért lehet, hogy ezt is megrendelem. Menő.<br />  Megcsóváltam a fejem, és inkább visszafordultam a monitoromhoz, nehogy olyasmit mondjak, amivel megbántom.</p>
<p>  Pár nap múlva megérkezett Svarci első kése. Meg kell hagyni, megcsinálta a házi feladatot. Átnézte a listát, amit küldtem neki, videókat nézett azokról a darabokról, amelyek érdekelték, majd az én véleményemet is kikérte. Miután megmutattam neki a saját példányomat, végül egy Civivi Elementum mellett döntött.<br />  Amikor néha rajtakaptam, hogy meló közben az asztal alatt azzal játszik, már tudtam, hogy elindult lefelé a lejtőn. A gyúrós oldalakat nem váltották le teljesen a késesek, de elég jelentős helyet kaptak Svarci kedvencei között, és elég gyakran kérdezgetett engem is különböző modellek kapcsán.<br />  Nemsokára megérkezett a második kés, egy Opinel (kajálni), aztán egy Mora (kiránduláshoz), aztán egy Böker Kaizen, ha elegáns alkalomra is kéne valami.<br />  Svarci feltűnt késes Facebook-csoportokban is, és egyre aktívabb lett; a kezdeti bizonytalan kommentek után már egy-egy önálló posztot is kirakott. Noha nem kötöttem az orrára, titokban büszke voltam magamra, hogy a harci akármitől végül ide jutottunk.<br />  Egy újabb péntek délután, amikor már többet néztük az órát, mint a monitorunkat, a szomszédos irodából bekukkantott egy srác.<br />  &#8211; Helló! Van egy késetek?<br />  &#8211; Mire kell? &#8211; kérdeztük egyszerre Svarcival, aztán mindkettőnkből kirobbant a röhögés.</p>

<p>Ha szeretnél naprakész lenni a bloggal kapcsolatban, akkor a <a href="https://www.facebook.com/VaszilijEdc">Facebook oldalon</a> találsz gyakori tartalmat.</p>
<p>Ha te is hozzájárulnál a késes tartalmak szaporításához, akkor a <a href="https://www.facebook.com/groups/434204628313605">Négyszögletű Pengeerdő</a> csoportban várunk szeretettel.</p>
</div>